package Utils;

public enum FileCreationState {
    FILE_CREATED_SUCCESSFULLY,
    FILE_ALREADY_EXISTS,
    DIRECTORY_DOES_NOT_EXIST,
    INVALID_PATH ,
    DIRECTORY_CREATION_FAILED ,
    DIRECTORY_CREATED_SUCCESSFULLY
}
